version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: history
    versions:
    - ">= 5.a, < 6"
  - dependency-name: less-loader
    versions:
    - ">= 7.a, < 8"
  - dependency-name: mobx
    versions:
    - ">= 5.a, < 6"
  - dependency-name: typescript
    versions:
    - ">= 3.6.a, < 3.7"
  - dependency-name: "@types/node"
    versions:
    - 14.14.23
    - 15.0.0
  - dependency-name: stylelint-config-standard
    versions:
    - 21.0.0
    - 22.0.0
  - dependency-name: postcss
    versions:
    - 8.2.11
  - dependency-name: webpack
    versions:
    - 5.34.0
  - dependency-name: css-loader
    versions:
    - 5.1.1
    - 5.1.2
    - 5.2.3
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: less-loader
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: cssnano
    versions:
    - 5.0.0
  - dependency-name: terser-webpack-plugin
    versions:
    - 5.1.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
    - 12.1.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
    - 12.1.0
    - 12.1.1
  - dependency-name: "@mapbox/rehype-prism"
    versions:
    - 0.6.0
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.0
    - 4.16.1
    - 4.17.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.0
    - 4.16.1
    - 4.17.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.0
    - 7.13.9
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: mobx
    versions:
    - 6.1.7
  - dependency-name: html-webpack-tags-plugin
    versions:
    - 3.0.0
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
  - dependency-name: react
    versions:
    - 17.0.1
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
